<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "accessmanager"
 *
 * Auto generated by Extension Builder 2017-05-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CGB AccessManager',
    'description' => 'Manage access rights for extbase objects',
    'category' => 'plugin',
    'author' => 'Christoph Balogh',
    'author_email' => 'cb@lustige-informatik.at',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80128',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
